version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile   # se seu Dockerfile tiver nome customizado
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./env.dev
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:17.0-alpine
    environment:
      POSTGRES_USER: bookstore_dev
      POSTGRES_PASSWORD: bookstore_dev
      POSTGRES_DB: bookstore_dev_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookstore_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
    driver: bridge

# (Opcional) se precisar persistir dados / uploads
#volumes:
#  media_data:
#  postgres_data:
